name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ${{ secrets.EC2_DIR }}
            git pull origin main
            sudo docker stop insightgpt || true
            sudo docker rm insightgpt || true
            sudo docker build -t insightgpt .
            sudo docker run -d \
              --name insightgpt \
              -p 8501:8501 \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              insightgpt
          EOF
